### ISSUE TITLE
test_core.py cannot pass on Python3.5

### ISSUE THREAD

**Issue by rim99** [cherrypy/cheroot#10]
While running pytest, I ran into a problem.

The `test_core.py` cannot pass on codes line.522 to line.555 .

```
# Get a partial file.
        if cherrypy.server.protocol_version == 'HTTP/1.1':
            self.getPage('/ranges/slice_file', [('Range', 'bytes=2-5')])
            self.assertStatus(206) # ERROR: Status ('404 Not Found') != 206
            self.assertHeader('Content-Type', 'text/html;charset=utf-8')
            self.assertHeader('Content-Range', 'bytes 2-5/14') # ERROR: 'Content-Range':'bytes 2-5/14' not in headers
            self.assertBody('llo,') # ERROR: much more than that

            # What happens with overlapping ranges (and out of order, too)?
            self.getPage('/ranges/slice_file', [('Range', 'bytes=4-6,2-5')])
            self.assertStatus(206) # ERROR: Status ('404 Not Found') != 206
            ct = self.assertHeader('Content-Type')
            expected_type = 'multipart/byteranges; boundary='
            self.assert_(ct.startswith(expected_type)) # AssertionError: False is not true
            boundary = ct[len(expected_type):]
            expected_body = ('\r\n--%s\r\n'
                             'Content-type: text/html\r\n'
                             'Content-range: bytes 4-6/14\r\n'
                             '\r\n'
                             'o, \r\n'
                             '--%s\r\n'
                             'Content-type: text/html\r\n'
                             'Content-range: bytes 2-5/14\r\n'
                             '\r\n'
                             'llo,\r\n'
                             '--%s--\r\n' % (boundary, boundary, boundary))
            self.assertBody(expected_body) # ERROR: much more than that
            self.assertHeader('Content-Length')

            self.getPage('/ranges/slice_file', [('Range', 'bytes=2300-2900')])
            self.assertStatus(416) # ERROR: Status ('404 Not Found') != 416
            self.assertHeader('Content-Range', 'bytes */14') # ERROR: 'Content-Range':'bytes */14' not in headers
```

I removed the original comments, and put test error messages as comments behind actually unpassed codes.

-----------------------

It looks like need a static file named static/index.html.

I try to create the file manually, which content is "Hello". But the response code is 416 other than 206.

---------------------

I set the content to be <html><head></head><body>Hello</body></html>.

The first ERROR is fixed, now it is the 2nd ERROR: 'Content-Range':'bytes 2-5/14' not in headers

-------

Right, it's "Hello, world."

I solved this, how can I remove  this issue?

**Comment by rim99** [comment]
It looks like need a static file `static/index.html`.

I tried to created the file manually, which content is "Hello". But the response code is 416 other than 206. 

Now I'm not sure what the content  should be?

**Comment by rim99** [comment]
I set the content to be `<html><head></head><body>Hello</body></html>`.

The first ERROR is fixed, now it is the 2nd ERROR: `ERROR: 'Content-Range':'bytes 2-5/14' not in headers`

**Comment by webknjaz** [comment]
You need to push the fix via separate feature (bugfix) branch and then create a PR.

**Comment by rim99** [comment]
#14 RP solved this issue

**Comment by webknjaz** [comment]
No, it didn't, unless merged.
