### ISSUE TITLE
Non-int Content-Length raises ValueError and returns 408 error

### ISSUE THREAD

**Issue by Dobatymo** [cherrypy/cheroot#100]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Describe the bug. What is the current behavior?**
If the Content-Length header has a value which cannot be converted to string a ValueError is raised which is not handled explicitly. A 408 Request Timeout is returned.

**What is the motivation / use case for changing the behavior?**
My logs are littered with entries like
```python-traceback
[13/Jun/2018:00:28:17] ENGINE ValueError("invalid literal for int() with base 10: b'<script>alert(Content-Length)</script>'",)
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\cheroot\server.py", line 1152, in communicate
    req.respond()
  File "C:\Program Files\Python35\lib\site-packages\cheroot\server.py", line 964, in respond
    cl = int(self.inheaders.get(b'Content-Length', 0))
ValueError: invalid literal for int() with base 10: b'<script>alert(Content-Length)</script>'
```

**To Reproduce**
Simply send a http request with a non-int content-length header.
```python
>>> import requests
>>> requests.get("https://cheroot.example", headers={"Content-Length":"asd"})
<Response [408]>
```

**Expected behavior**
Explicitly handle that case and return 'Bad Request' or whatever the correct status code for this situation is.

**Environment**
- Cheroot version: 6.0.0
- CherryPy version: 14.0.1
- Python version: 3.5.4
- OS: Windows
- Browser: all

I know I am not using the latest version, but the code looks like it should still give the same error.

**Comment by nosmokingbandit** [comment]
On the current release Cheroot returns a 500 error, which is less descriptive. I've submitted a PR that addresses this.
