### ISSUE TITLE
Lock setuptools_scm version to prevent breaking updates

### ISSUE THREAD

**Issue by macbeth322** [cherrypy/cheroot#107]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Describe the bug. What is the current behavior?**
Currently, `setup.py` has `setup_requires` of `setuptools_scm>=1.15.0` https://github.com/cherrypy/cheroot/blob/master/setup.py#L79
Current `3.x` versions of `setuptools_scm` have breaking issues which cascade to cheroot. Since `setup_requires` is no lockable by normal means such as a `requirements.txt` or `Pipfile.lock`, it makes it very difficult to avoid this issue.

**What is the motivation / use case for changing the behavior?**
Changing the `setup_requires` to use absolute version numbers would prevent these unlockable dependencies from updating and pulling in breaking changes.

**To Reproduce**

`pip install cheroot --no-binary :all:` in python3 fails

**Expected behavior**

`pip install cheroot  --no-binary :all:` succeeds

**Details**

https://github.com/pypa/setuptools_scm/issues/286
The issue has been addressed but not yet released to pypi.

I would be willing to make a pull request to address this issue if this is something you are willing to do.

**Comment by webknjaz** [comment]
@jaraco what do you think?

**Comment by jaraco** [comment]
I'd grown comfortable with setuptools_scm being mostly stable and unchanging. If it's going to start making backward-incompatible releases, then it may make sense to put an upper bound on the releases. However, looking at the upstream issue, what you see is a bug that was introduced unintentionally. In that case, while pinning setuptools_scm will prevent this sort of issue, it also introduces technical debt - requiring developers to periodically bump the pinned version. Moreover, with a build-time dependency like setuptools_scm, I've seen problems with pinning to a specific version, where the environment might have a later version installed than required. If pinned, the dependency won't be satisfied and the package won't install unless the exact right version is present.

In my experience, leaving it unpinned is more lenient and less disruptive. I don't think there's much to do here, except maybe pin _against_ the broken versions (i.e. `>=1.15.0,!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3`). I'd rather leave it as-is.
