### ISSUE TITLE
v6.5.0 release failed

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#112]
It looks like doctests are failing under macOS

**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Describe the bug. What is the current behavior?**

**What is the motivation / use case for changing the behavior?**
Fix release process

**To Reproduce**

https://travis-ci.org/cherrypy/cheroot/builds/422117270

**Expected behavior**

Release published on PyPI

**Details**

**Environment**

- Cheroot version: 6.5.0
- CherryPy version: NA
- Python version: 3.6/3.7
- OS: macOS @ Travis CI
- Browser: N/A

**Additional context**

**Comment by jaraco** [comment]
I just ran the tests on my mac at 9f77c315, and they passed.

**Comment by jaraco** [comment]
The issue for at least one of the failed builds is pytest-dev/pytest#3888, which explains why the tests didn't fail on my machine, which picked up a later version of pytest (3.7.4).

That issue was addressed in jaraco/skeleton@5633116de3, so I'll merge in that change and other ones, which should address the issue and maybe others.

**Comment by jaraco** [comment]
In 85c6dfa7, I've merged the skeleton, which should fix the test failures. I've run out of time to work on it, though, so I'm going to have to leave it and hope for the best.

**Comment by webknjaz** [comment]
Thanks, I'll restart that canceled job in this build to make it publish dists: https://travis-ci.org/cherrypy/cheroot/jobs/422117286

**Comment by webknjaz** [comment]
@jaraco I'll revert a few changes from that merge, which break things (Python 3.7 job, markdown rendering)
