### ISSUE TITLE
Slow writes for large response body for HTTPS connection 

### ISSUE THREAD

**Issue by nav-agarwal** [cherrypy/cheroot#133]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Describe the bug. What is the current behavior?**

Performance Bug
Slow writes observed(<2MB/permin) in case of large response body(around 300MB) when using HTTPS connection

**What is the motivation / use case for changing the behavior?**
Poor download performance for HTTPS connection on local server

**To Reproduce**

1. Setup HTTPS cherrypy server
 ```python
import cherrypy
class Root(object):
    @cherrypy.expose
    def index(self):
        cherrypy.log("Inside index")
        buff = "a" * 1024 * 1024 * 300
        return buff

if __name__ == '__main__':
    config = {
            'server.ssl_certificate': 'cert.pem',
            'server.ssl_private_key': 'privkey.pem',
            'server.ssl_module' : 'pyopenssl',
    }
    cherrypy.config.update(config)
    cherrypy.quickstart(Root())

```
2. Make requests
```python
import requests
r = requests.post("https://localhost:8080", verify=False)
```

**Expected behavior**
On HTTP connection same requests finishes within seconds

**Details**
Root Cause:Bug is due to following code in write function of makefile. This function is used for HTTPS connection writes only:
`data = data[bytes_sent:]`
Here we are copying almost complete buffer after every socket write. In python. slices leads to copy of remaining buffere as strings are immutable.
Possible fix:
Do chunking in small buffers by matining idx till which write has happened

**Environment**

- Cheroot version: 6.5.2
- CherryPy version: 17.4.0
- Python version: 2.7.13
- OS: Ubuntu 14.04.5 LTS
- Browser: -

**Additional context**
Performance Bug

**Comment by webknjaz** [comment]
@nav-agarwal try out #134 

Also, have you tried Python 3 version? It should be better optimized.

**Comment by nav-agarwal** [comment]
@webknjaz : 

1. I have corrected http to https in my request code
2. I will try to test it with python3 and upload results in couple of days, but my gut feeling is that it will have same problems.

**Comment by nav-agarwal** [comment]
@webknjaz : Fix is working fine. Thanks for the

**Comment by nav-agarwal** [comment]
@webknjaz : Fix is working fine. Thanks for the quick fix
