### ISSUE TITLE
cheroot.wsgi lacks ssl support

### ISSUE THREAD

**Issue by vanrein** [cherrypy/cheroot#135]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request
- [ ] question about the decisions made in the repository

**Is your feature request related to a problem? Please describe.**
I was trying to use `cheroot.wsgi` with an `ssl_module` but, as far as I can tell, this is not a supported combination.  I tried the documentation and code to find the link.

**Describe the solution you'd like**
A parameter in `cheroot.wsgi.Server` that welcomes a subclass of `cheroot.ssl.Adapter` would be welcome.

**Describe alternatives you've considered**
The `HTTPServer` supports it, but this is not a WSGI `Gateway`.

**Additional context**
N/A

**Comment by vanrein** [comment]
Apologies.  I failed to get this going because I misspelled `.ssl_adapter` as `.ssl_adaptor` in my code, and so I concluded that this didn't work for WSGI.  It now uses the SSL adapter as I had expected.  Note that the WSGI documentation is very unclear if this should work, I would not have filed the issue had it been more clearly explained there.

**Comment by webknjaz** [comment]
Hi @vanrein, feel free to contribute to docs. I'd very appreciate this.
