### ISSUE TITLE
Travis CI: Should pypy and pypy3 be upgraded to v6.0.0?

### ISSUE THREAD

**Issue by cclauss** [cherrypy/cheroot#136]
Update: Blocked by https://travis-ci.community/t/support-for-pypy-pypy3-v6-0-python/1249 (travis-ci/travis-ci#9542)

**I'm submitting a ...**
- [ ] bug report
- [X] feature request
- [ ] question about the decisions made in the repository

**Is your feature request related to a problem? Please describe.**

The current .travis.yml seems to be [running old PyPy versions](https://github.com/cherrypy/cheroot/blob/master/.travis.yml#L12-L13) and the comments are saying that PyPy does not work on macOS.  On my Mac...

$ __pypy -V__
```
Python 2.7.13 (ab0b9caf307db6592905a80b8faffd69b39005b8, Jun 17 2018, 13:50:59)
[PyPy 6.0.0 with GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```
$ __pypy3 -V__
```
Python 3.5.3 (fdd60ed87e941677e8ea11acf9f1819466521bf2, Apr 26 2018, 01:25:35)
[PyPy 6.0.0 with GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

**Describe the solution you'd like**

Travis CI tests with PyPy v6 and PyPy3 v6

**Describe alternatives you've considered**

**Additional context**

**Comment by webknjaz** [comment]
Hi, I'd like to do this, but Travis seems to not have this version supported just yet. However, it might make sense to enable it for macOS builds.

**Comment by webknjaz** [comment]
@cclauss mind sending a PR for macOS builds?

**Comment by webknjaz** [comment]
Ref https://github.com/travis-ci/travis-ci/issues/9542
