### ISSUE TITLE
[TODO] Add valid .gitignore and .gitattributes

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#15]

**Comment by jaraco** [comment]
FWIW, I'm happy with it like it is.

**Comment by webknjaz** [comment]
I'd drop-in this one https://www.gitignore.io/api/python, which for example ignores tox artifacts, build artifacts, logs etc.

Regarding `.gitattributes`, it usually helps when one messes up with their line breaks or uses Windows :)
I saw this enough times to want it be in every project: one changes a single char, but in diff the whole file is removed and added again. This is complete mess, when it comes to review and it's even much more horrible when someone commits that directly into the repo.
