### ISSUE TITLE
setup.cfg shouldn't supply 'license'

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#154]
The license parameter to setup should be removed. The docs for that parameter indicate that the parameter is only intended when the license can't be specified by the trove classifiers.

**Comment by webknjaz** [comment]
@serhii73 do you want to give it a try?

**Comment by serhii73** [comment]
@webknjaz Yes. It will be brilliant for me.
@webknjaz 
I try to send PR on Monday.
I not sure I fully understand the task.
https://github.com/cherrypy/cheroot/blob/master/setup.cfg - I need work only with this file?
Just to remove the line `license_file = LICENSE.md`?
Did I confuse it?

**Comment by jaraco** [comment]
@serhii73 Glad for the extra help. You don't want to remove `license_file` but instead remove `license`.

**Comment by serhii73** [comment]
I read it https://packaging.python.org/guides/distributing-packages-using-setuptools/#license
And fully understand, I think, why don't need this line(the license argument).
