### ISSUE TITLE
Project should avoid invoking setup.py

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#155]
As easy_install and eggs are deprecated and as setup_requires of 'setuptools_scm' indicates for easy_install to install an egg if the requirement isn't met, any invocation of setup.py that hasn't already satisfied the setup_requires will invoke easy install. Let's work to remove those invocations. Feel free to draw inspiration from jaraco/skeleton, which demonstrates how to not to rely on setup_requires while still checking the docs (pytest-checkdocs).

**Comment by webknjaz** [comment]
I'm not sure how it's related to `easy_install`. How are we supposed to build dists, then?

**Comment by jaraco** [comment]
[pep517](https://pypi.org/project/pep517)) `build`. See jaraco/skeleton for how it's done.

**Comment by webknjaz** [comment]
Solved by #226
