### ISSUE TITLE
Setuptools version required for sdist is old

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#156]
The pyproject.toml specifies setuptools 30.x, but for python_requires to be supported in declarative config, setuptools 34.4 is required. This bug was fixed in jaraco/skeleton.

**Comment by webknjaz** [comment]
I'd want to add a shim for this to `setup.py`

**Comment by jaraco** [comment]
As of the 8.0 release, cheroot now requires setuptools 34.4.
