### ISSUE TITLE
ChunkedRFile fails with pyopenssl.SSLFileobjectStreamReader

### ISSUE THREAD

**Issue by mar10** [cherrypy/cheroot#162]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

📋 **Environment**
- Cheroot version: 6.4.5 and master
- Python version: 3.7.X
- OS: macOS

📋 **Additional context**
Exception
```pytb
Traceback (most recent call last):
  File "/Users/martin/prj/git/wsgidav/wsgidav/request_server.py", line 830, in do_PUT
    fileobj.writelines(data_stream)
  File "/Users/martin/prj/git/wsgidav/wsgidav/request_server.py", line 682, in _stream_data_chunked
    buf = environ["wsgi.input"].read(block_size)
  File "/Users/martin/.local/share/virtualenvs/wsgidav-9PbuForg/lib/python3.7/site-packages/cheroot/server.py", line 524, in read
    self._fetch()
  File "/Users/martin/.local/share/virtualenvs/wsgidav-9PbuForg/lib/python3.7/site-packages/cheroot/server.py", line 470, in _fetch
    line = self.rfile.readline()
TypeError: readline() missing 1 required positional argument: 'size'
```

The wsgi.input value contains a cheroot.server.ChunkedRFile object, which in turn contains a cheroot.ssl.pyopenssl.SSLFileobjectStreamReader:

<img width="924" alt="bildschirmfoto 2019-01-06 um 21 25 46" src="https://user-images.githubusercontent.com/41663/50741173-f5360d80-11f9-11e9-8011-f3462a007830.png">

cheroot/server.py", line 470, in _fetch() calls 
```py
    def _fetch(self):
        if self.closed:
            return

        line = self.rfile.readline()
```

which is not valid, because `size` is mandatory in /cheroot/ssl/pyopenssl.py readline(size)
```py
class SSLFileobjectStreamReader(SSLFileobjectMixin, StreamReader):
    """SSL file object attached to a socket object."""

class SSLFileobjectMixin:
    """Base mixin for an SSL socket stream."""
    ...
    def readline(self, size):
        """Receive message of a size from the socket."""
```

**Comment by webknjaz** [comment]
Oh thanks for the report!

**Comment by webknjaz** [comment]
Looks like we should have `readline(self, size=-1)` there as per https://docs.python.org/3/library/io.html#io.IOBase.readline

**Comment by webknjaz** [comment]
@mar10 could you please check the current `master`?
