### ISSUE TITLE
New option to drop headers that contain underscores

### ISSUE THREAD

**Issue by mar10** [cherrypy/cheroot#17]
I'd like to propose a new option to drop headers that contain underscores ('_').

Cheroot / CherryPy convert HTTP headers for WSGI to upper case and replace hyphen ('-') with  underscore ('_'):

```py
env.update(
    ('HTTP_' + bton(k).upper().replace('-', '_'), bton(v))
    for k, v in req.inheaders.items()
)
```   

So this headers

```py
headers = {"Sm-User": "val1",
           "Sm_User": "val2",}
res = requests.get("http://127.0.0.1:8080", headers=headers)
```

will result in a **single** WSGI environment entry `"HTTP_SM_USER": "val1"` *or* `"HTTP_SM_USER": "val2".` 
(The concrete behavior is undefined, since the order of dict key iteration is hard to control.)

### Proposed solution

This *could* be fixed by modifying the wsgi server code above, but I would suggest to drop those headers in the core code.

While underscores in header fields are allowed ([rfc7230](https://tools.ietf.org/html/rfc7230#section-3.2)), they are uncommon, AFAIK.  
For example Apache and nginx seem to drop them by default:
http://stackoverflow.com/a/18205049/19166
http://stackoverflow.com/a/22856867/19166

So a solution could look like this:
```py
def read_headers(rfile, hdict=None, drop_underscores=False):
    ...
    while True:
        line = rfile.readline()
            ...
            if drop_underscores and '_' in k:
                continue
            k = k.strip().title()
            v = v.strip()
            hname = k
            ...
```

I tried to prepare a PR, but I could need some advice how and where to make this configurable:

```py
        try:
            read_headers(self.rfile, self.inheaders)
            # Configurable using "`server.underscores_in_headers": False`
            drop_underscores = not self.server.server_adapter.underscores_in_headers
            read_headers(self.rfile, self.inheaders, drop_underscores)
        except ValueError:
            ex = sys.exc_info()[1]
            self.simple_response('400 Bad Request', ex.args[0])
```

For example I tried adding this to cheroot.HTTPServer:

```py
class HTTPServer(object):
    ...
    underscores_in_headers = True
    """If False, silently discards headers containing underscores ('_')."""
```

and then make it configurable from cherrypy like so:

```py
cherrypy.config.update({"server.underscores_in_headers": False})
cherrypy.quickstart(HelloWorld())
``` 
=> this seems to set the attribute on the ServerAdapter instead of the HttpServer.

or 

```py
cherrypy.quickstart(HelloWorld(), config={
    "/": {
        "server.underscores_in_headers": False,
        }
    })
``` 

doesn't work, because the `server`namespace is not registered when quickstart is running?

**Comment by webknjaz** [comment]
Hello Martin,

I like your idea overall. I'm currently not sure about the config, perhaps I'll figure this out later.
You may proceed with PR and decide about the feature toggle later during review.

**Comment by mar10** [comment]
Maybe 'drop_underscore_headers' is a better option name than 'underscores_in_headers'.
Default should probably be `False` for now to avoid surprises. (But if I am not mistaken, Apache and nginx seem to have this enabled by default.)

The implementation is trivial, however I don't know what is the best way to configure it.
Configuration should be possible when Cheroot is used directly, but we should also offer to configure this through the CherryPy framework

We could
- configure it as attribute of `server.HTTPServer`  
  Don't know if this a good place, but `max_request_header_size`lives there for example.  
  But how could a user configure it using th config.ini or using`@cherrypy.config(**{...})`?
- Configuration-wise I think that :
  `@cherrypy.config(**{'server.drop_underscore_headers': True})` 
  would be intuitive for a CherryPy user.
  But how can this setting be accessed from Cheroot code?

Any advice?

**Comment by jaraco** [comment]
Can you update the original post to describe (or link to) the original _problem_ description (explaining why someone would care about this issue)?

I can't help but feel like this issue is a problem with the WSGI spec, since it's WSGI that's informing the choice to translate lowercase and dash-separated names to uppercase, underscore-separated names. It seems to me the issue doesn't apply only to the dash/underscore translation but also with the case sensitivity. This translation doesn't happen in the base HTTPServer.

This finding makes me wonder if the wsgi spec has anything to say about the handling of conflated headers as you describe.

**Comment by jaraco** [comment]
Reading [PEP 3333](https://www.python.org/dev/peps/pep-3333/#environ-variables) gives me little insight.

**Comment by mar10** [comment]
I think it may have security implications:

Consider a CherryPy application running behind a proxy that does NTLM or SAML
authentication. 
If the user is authenticated, a header field will be injected, otherwise this header is removed or emptied.
Since the app is only reachable through the proxy it will trust this field.

Assume the field is named `X-Auth-User-Name`.

An attacker that is not authorized or authorized with a restricted account could issue an ajax request with additional headers, e.g. 
`X_Auth-User_name: admin`, `X_Auth_User-name: admin`, …
(Easy with browser plugins, for example.)

With a bit of luck, CherryPy will replace the protected field with the
elevated variant. 

I don’t think that this is strictly a bug in Cheroot (since the proxy could filter this out), but the proposed change would make it easier to harden the application.

**Comment by tlandschoff-scale** [comment]
We actually fell over this, in that a client could overwrite the HTTP headers of a proxy. We discovered this ticket and the solution.

But using `DropUnderscoreHeaderReader` actually breaks the service completely as it expects a native str, but the header is passed as a byte string:

```python
Traceback (most recent call last):
    File ".../python3.7/site-packages/cheroot/server.py", line 1274, in communicate
    req.parse_request()
  File ".../python3.7/site-packages/cheroot/server.py", line 716, in parse_request
    success = self.read_request_headers()
  File ".../python3.7/site-packages/cheroot/server.py", line 971, in read_request_headers
    self.header_reader(self.rfile, self.inheaders)
  File ".../python3.7/site-packages/cheroot/server.py", line 226, in __call__
    if not self._allow_header(k):
  File ".../python3.7/site-packages/cheroot/server.py", line 250, in _allow_header
    return orig and '_' not in key_name
TypeError: a bytes-like object is required, not 'str'
```

This tells me

a) this class did never work
b) everybody using cheroot so far is prone to header spoofing attacks

I'd really like cheroot to be secure by default...

Greetings, Torsten
