### ISSUE TITLE
cheroot 6.5.4 traceback for python 3.6 complaining about backports.functools_lru_cache requirement not being met

### ISSUE THREAD

**Issue by williamh** [cherrypy/cheroot#181]
❓ **I'm submitting a ...**
- [X] 🐞 bug report

🐞 **Describe the bug. What is the current behavior?**

cheroot crashes with a traceback on python 3.6 on Gentoo Linux, but it shouldn't because the function it needs is in the standard library.

💡 **To Reproduce**

1. Run '...'
2. Make request '....'
3. See error
```python-traceback
whubbs@whubbs1 ~ $ cheroot
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/cheroot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.functools_lru_cache' distribution was not found and is required by cheroot
whubbs@whubbs1 ~ $ python
Python 3.6.5 (default, Jul 24 2018, 10:46:29)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from functools import lru_cache
>>>
whubbs@whubbs1 ~ $
```
💡 **Expected behavior**

No crash, because as shown, the function is available.

📋 **Details**

See above.

📋 **Environment**
- Cheroot version: 6.5.4
- Python version: 3.6.5
- OS: Linux

📋 **Additional context**

I am a packager for Gentoo Linux working on upgrading cheroot/cherrypy for us.

**Comment by williamh** [comment]
This pull request is related:
https://github.com/CherryPy/cheroot/pull/85

**Comment by webknjaz** [comment]
@williamh I bet you have some outdated setuptools. Can you check that? How did you build the dist? How did you install it?

**Comment by webknjaz** [comment]
`pkg_resources` is shipped as a part of `setuptools` dist. That's what causes traceback, not Cheroot's own code.
That change in #85 was reverted via ea8acd0786cfb7435011f018897fbfd0f9759415.

@williamh feel free to `epatch` this dependency away in your ebuild.

**Comment by webknjaz** [comment]
I'm pretty sure this has been addressed as per above...
