### ISSUE TITLE
Tests failing on pip 19.1

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#194]
Like many projects relying on `pip install -e`, this project is failing following the release of pip 19.1 due to pypa/pip#6434. There's a fix in jaraco/skeleton from which you might draw inspiration.

**Comment by jaraco** [comment]
This issue [blocked the automated release of cheroot 6.5.5](https://travis-ci.org/cherrypy/cheroot/builds/526287137), but I've made the release manually.

**Comment by webknjaz** [comment]
I'd copy-paste the one-liner from Molecule... Can't do now, boarding the ✈
