### ISSUE TITLE
cheroot/server.py:968: TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by alpire** [cherrypy/cheroot#218]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

cherrypy returns a 500 on some malformed HTTP request due to a missing argument in a format string in [server.read_request_line](https://github.com/cherrypy/cheroot/blob/master/cheroot/server.py#L968).

❓ **What is the motivation / use case for changing the behavior?**

I believe that web servers should not return 500s in general. If you disagree, feel free to close this issue. Otherwise, I'll keep fuzzing cherrypy and reporting issues.

💡 **To Reproduce**

1. Run a cherrypy server, like the following:
```python
import cherrypy

class HelloWorld(object):
    @cherrypy.expose
    def index(self):
        return "Hello World!"

cherrypy.quickstart(HelloWorld())
```

2. Make request with `echo -ne "GET / HTTP/1\r\n\r\n" | nc localhost 8080`
3. See the 500 response

💡 **Expected behavior**

I would expect a 4xx request, probably a 400

📋 **Details**

```
[09/Aug/2019:15:50:52] ENGINE TypeError('not enough arguments for format string')
Traceback (most recent call last):
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/cheroot/server.py", line 1263, in communicate
    req.parse_request()
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/cheroot/server.py", line 719, in parse_request
    success = self.read_request_line()
  File "/Users/apr/.pyenv/versions/3.7.2/lib/python3.7/site-packages/cheroot/server.py", line 968, in read_request_line
    self.response_protocol = 'HTTP/%s.%s' % min(rp, sp)
TypeError: not enough arguments for format string
```

📋 **Environment**

- Cheroot version: 6.5.5
- CherryPy version: 18.1.2
- Python version: 3.7.2
- OS: MacOS Mojave
- Browser: N/A

**Comment by webknjaz** [comment]
Thanks for the report! PR is welcome :)

P.S. I'm thinking of migrating to Hyper11: https://github.com/cherrypy/cheroot/issues/201 but that shouldn't stop us from making bug fixes.
