### ISSUE TITLE
Unable to resolve merge commit due to pre-commit checks

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#223]
I'm trying to resolve a merge conflict locally, but when I do, the pre-commit checks reject my commit:

```
cheroot dcermak-master $ git merge master                                                                                                    
Auto-merging setup.cfg
Auto-merging CHANGES.rst
CONFLICT (content): Merge conflict in CHANGES.rst
Automatic merge failed; fix conflicts and then commit the result.
cheroot dcermak-master $ git mergetool                                                                                                       
Merging:
CHANGES.rst

Normal merge conflict for 'CHANGES.rst':
  {local}: modified file
  {remote}: modified file
cheroot dcermak-master $ git commit                                                                                                          
[WARNING] Unexpected key(s) present on git://github.com/pre-commit/pre-commit-hooks => name-tests-test: include
[INFO] Checking merge-conflict files only.
Add trailing commas..................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Flake8...............................................(no files to check)Skipped
Check for merge conflicts................................................Failed
hookid: check-merge-conflict

Merge conflict string "=======
" found in CHANGES.rst:240
Merge conflict string "=======
" found in CHANGES.rst:248

Fix double quoted strings............................(no files to check)Skipped
Fix End of Files.........................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Debug Statements (Python)............................(no files to check)Skipped
Check for added large files..............................................Passed
Check python ast.....................................(no files to check)Skipped
Check for byte-order marker..............................................Passed
Check for case conflicts.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Detect Private Key.......................................................Passed
Fix requirements.txt.................................(no files to check)Skipped
Verifying PEP257 Compliance..........................(no files to check)Skipped
Tabs remover.............................................................Passed
HTML img tag alt text checker........................(no files to check)Skipped
cheroot dcermak-master $ git status                                                                                                          
On branch dcermak-master
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:
        modified:   .gitignore
        modified:   .travis.yml
        modified:   CHANGES.rst
        modified:   cheroot/_compat.py
        modified:   cheroot/server.py
        modified:   cheroot/test/conftest.py
        modified:   cheroot/test/test_server.py
        modified:   cheroot/test/test_ssl.py
        modified:   setup.cfg

```

I suspect this finding reveals a bug in pre-commit, but I don't have time to shave that yak.

**Comment by jaraco** [comment]
Gah. This issue was reported in pre-commit/pre-commit-hooks#100 and the recommendation is "don't use that header length"... except that's not really an option for us, as the length depends on the version and the version is already tagged. Another option might be to exclude the file.... but what if it has merge conflicts?

**Comment by jaraco** [comment]
I was able to complete the commit by running `pre-commit uninstall`.

**Comment by webknjaz** [comment]
You can always `git commit -n` which disables pre-commit hooks.

**Comment by webknjaz** [comment]
I guess that this happens only if git stops on a merge conflict. So let's use `merge=union` and see how it goes.

**Comment by jaraco** [comment]
> I guess that this happens only if git stops on a merge conflict. So let's use `merge=union` and see how it goes.

I don't think so. The pre-commit hook was failing simply because the pending change to the changelog contains an RST header of length 7 and using `=` characters.

The recommendation in the check is to `exclude` rst files.

I'm pretty sure if you were to apply this diff to the file, it would fail the check:

```
 cheroot main @ git diff
diff --git a/CHANGES.rst b/CHANGES.rst
index c4b27d5e..d5c6c3ed 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -1,3 +1,6 @@
+Newtitl
+=======
+
 .. scm-version-title:: v11.0.0
 
 - :issue:`565`: Cheroot requires Python 3.8 or later.
 - ```

However, looking at the latest changelog, it no longer includes literal headings but instead `scm-version-title` directives, so that's probably sidestepped the issue.

**Comment by webknjaz** [comment]
> The recommendation in the check is to `exclude` rst files.

You're right. I remember that I did use `exclude` in the past for something like README... Another solution could be to stop using `=====` in RST and switch to any other underlying character.

**Comment by jaraco** [comment]
> Another solution could be to stop using `=====` in RST and switch to any other underlying character.

I've heard this recommendation before, but it's not a good one. A tool that's unrelated to the documentation shouldn't be enforcing structural constraints on the documentation. In jaraco/skeleton, I've adopted towncrier, which uses `=` as the default heading, and it's also possibly the most common heading for RST. It's also the first [documented convention](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections) a user is exposed to. Others have proposed that users avoid headings of length 7, but that also isn't viable if one has configured Sphinx to be picky about lint. If check-merge-conflict wants to be hostile to that level of heading, it should probably declare non-support for RST files or get RST files to recommend against using `=` headings (and recommend something different) so that downstream projects like towncrier and jaraco/skeleton can adopt that change as a best practice.
