### ISSUE TITLE
Appveyor tests failing on Python 2.7

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#227]
See [this build](https://ci.appveyor.com/project/CherryPy/cheroot/builds/27698452/job/ycolss9esm3ngl1a) for an example. The virtualenv gets created with an old version of pip and while tox is in the process of upgrading pip to `>=9`, it's already too late because `tox >= 3.11.2` or `tox-run-command >= 0.4.` creates an implied dependency on more_itertools, which gets resolved before pip is recent enough to honor the `python_requires`.

This environment needs to be updated to upgrade virtualenv before invoking tox... or maybe drop Python 2.7 support.

**Comment by webknjaz** [comment]
It's been fixed by https://github.com/cherrypy/cheroot/commit/2900f6f6210a30edbcf24e998d9c7afb3023ff94 and also upstream https://github.com/tox-dev/tox/pull/1429.

I believe you just forgot to rebase your PR.

P.S. Also reported to https://github.com/jaraco/zipp/issues/16.

**Comment by webknjaz** [comment]
Closing this as it'll be fixed next time tox does the release and a workaround has been applied to AppVeyor config already.
