### ISSUE TITLE
Latest releases are only tags?

### ISSUE THREAD

**Issue by mar10** [cherrypy/cheroot#235]
Probably not a big deal, but it seems that starting with v6.5.7 releases are not marked as such in GitHub (PyPI visions are correct):
![image](https://user-images.githubusercontent.com/41663/66554467-573aef00-eb4d-11e9-8289-ef8d7c84e526.png)

**Comment by webknjaz** [comment]
This needs manual work ATM, sometimes I do it. "Releases" are just Git tags with extra metadata but we don't upload dists there anyway.

**Comment by mar10** [comment]
Never mind, just was not sure if you are aware

**Comment by webknjaz** [comment]
Yep. Maybe in some future CI/CD enhancements, I'll enable auto-creation of releases...
