### ISSUE TITLE
ModuleNotFoundError: No module named 'cheroot' v8.2.1

### ISSUE THREAD

**Issue by KrishnaAnanthi** [cherrypy/cheroot#244]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

Till v8.2.0 things were working fine. from friday i am getting no module found error for the below line **from cheroot.wsgi import Server**
```python-traceback
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/edge/siemens/automation/server/__main__.py", line 18, in <module>
    from server.server import Inventory
  File "server.py", line 22, in init server
ModuleNotFoundError: No module named 'cheroot'
```

❓ **What is the motivation / use case for changing the behavior?**

💡 **To Reproduce**

1. Run '...'
2. Make request '....'
3. See error

💡 **Expected behavior**

📋 **Details**

📋 **Environment**

- Cheroot version:8.2.0
- CherryPy version:18.3.0 (if applicable)
- Python version: 3.7
- OS: debian
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

📋 **Additional context**

**Comment by webknjaz** [comment]
Have you tried reinstalling it? Looks like an issue in your env.

**Comment by KrishnaAnanthi** [comment]
actually its inside docker environment

**Comment by webknjaz** [comment]
It doesn't matter. It's a problem in your env, I've just verified that it works
```console
$ cheroot-8.2.1-venv/bin/python -c 'from cheroot.wsgi import Server'  
```
I've also unpacked the wheel and there's nothing out of ordinary inside.

**Comment by KrishnaAnanthi** [comment]
After one day it started working without any changes

**Comment by webknjaz** [comment]
It's likely that it happened because your module was called `server.py`
