### ISSUE TITLE
`started_request` can not judge socket timeout just because system can not

### ISSUE THREAD

**Issue by MrZedNavie** [cherrypy/cheroot#246]
❓ **I'm submitting a ...**
- [ ] 🐞 bug report
- [X] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Is your feature request related to a problem? Please describe.**

[not filled in]

🐣 **Describe the solution you'd like**

`httpconnection` `communicate()`, it will catch socket timeout exception, but it accross `request_seen` and `started_request` to judge the reason for socket timeout.
First judge `request_seen` whether it is `True`. If it is `True`, it proves that the system response is slow, then it should not respond to 408.
If `request_seen` is `False`, it proves that the request has not been processed, but it needs to be judged whether the data is not received or the processing is slow.
if we `recv` data (the first request line), then, `started_request` is `true`, but If the system is slower to process next and the other data has arrived, we do not processed in time, it will lead to timeout, so we can not response 408, but we did

📋 **Describe alternatives you've considered**

[not filled in]

📋 **Additional context**

[not filled in]

**Comment by MrZedNavie** [comment]
except socket.error as ex:
            errnum = ex.args[0]
            timeout_errs = 'timed out', 'The read operation timed out'
            if errnum in timeout_errs:
                if (not request_seen) or (req and req.started_request):
                    self._conditional_error(req, '408 Request Timeout')
at communicate function，the request_seen is true，Isn't started_request necessarily true?

**Comment by webknjaz** [comment]
FYI when you add text between `<!--` and `-->`, it's invisible.

**Comment by webknjaz** [comment]
*/me unwrapped the hidden text*

**Comment by webknjaz** [comment]
@MrZedNavie could you please rephrase your question? I'm having a hard time trying to understand what you want here.
