### ISSUE TITLE
cheroot breaking with jaraco.functools 3.0.0 release

### ISSUE THREAD

**Issue by adityatoshniwal** [cherrypy/cheroot#258]
❓ **I'm submitting a ...**
- [x] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
I've have wheel package of my application which uses cheroot. But now when I try to install the wheel on Python 3.5, cheroot does not install as jaraco.functool 3.0.0 does not work below Python 3.6, which indirectly makes cheroot to work only above 3.6

❓ **What is the motivation / use case for changing the behavior?**
I think jaraco.functools==2.0 should be pinned

💡 **To Reproduce**

Download the wheel file - https://ftp.postgresql.org/pub/pgadmin/pgadmin4/snapshots/2019-12-24/pgadmin4-4.16-py2.py3-none-any.whl
and install in a venv with Python 3.5

📋 **Details**

`Requirement already satisfied: more-itertools>=2.6 in ./pgwhl/lib/python3.5/site-packages (from cheroot==8.2.1->pgadmin4==4.16) (8.0.2)
Requirement already satisfied: jaraco.functools in ./pgwhl/lib/python3.5/site-packages (from cheroot==8.2.1->pgadmin4==4.16) (3.0.0)
ERROR: Package 'jaraco.functools' requires a different Python: 3.5.2 not in '>=3.6'
`

📋 **Environment**

- Cheroot version: 8.2.1
- Python version: 3.5.2
- OS: Ubuntu 16
- Browser: all

**Comment by webknjaz** [comment]
Your Pip is either outdated or you use it incorrectly. Our deps state that any version of `jaraco.functools` will satisfy the requirements and Pip will select what it thinks is best for your env. Upgrade your Pip.

Also, suggesting us to pin the dep is harmful — libs must almost never do this. Deps (including transitive deps) should be pinned on the end-user's application side as your env should be pinned to be reproducible.
I suggest you use `pip-tools` (best to also pin dist hashes).
Ref: https://hynek.me/articles/python-app-deps-2018/#pip-tools--everything-old-is-new-again
Ref: https://github.com/jazzband/pip-tools/#example-usage-for-pip-compile

**Comment by adityatoshniwal** [comment]
Thank you @webknjaz.
I'll check my environment.

**Comment by adityatoshniwal** [comment]
@webknjaz - Yes, you were right. I upgraded pip and it worked fine. Sorry for the trouble. Thanks again.
