### ISSUE TITLE
[TODO] Change Travis CI config to use newly presented build stages feature

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#28]
Refs:
* https://blog.travis-ci.com/2017-05-11-introducing-build-stages
* https://docs.travis-ci.com/user/build-stages#Examples

*Note: I'm going to move PYPI deployment to separate stage, so it would wait for tests in all envs to complete.*

**Comment by jaraco** [comment]
Sounds good to me. I've always found it awkward to select one "blessed" version for cutting releases. I do want the releases to be cut using the latest stable Python version, though. Consider contributing the changes to [jaraco/skeleton](/jaraco/skeleton) so they can be applied to many more projects than just this one.
