### ISSUE TITLE
[TODO] Refactor `cheroot.connections` to use `selectors.get_map()`

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#304]
❓ **I'm submitting a ...**
- [ ] 🐞 bug report
- [X] 🐣 refactoring request
- [ ] ❓ question about the decisions made in the repository

🐞 **Is your feature request related to a problem? Please describe.**

_@liamstask suggested in https://github.com/cherrypy/cheroot/pull/301/files#r458248844:_
> not strictly necessary, but it would be preferable to avoid re-registering and unregistering all sockets each time this `select()`s - each `register()` and `unregister()` will typically incur a syscall per socket, which reduces performance unnecessarily, particularly with large numbers of sockets.
>
> the selector already maintains a map of which sockets are registered - see [`get_map()`](https://docs.python.org/3/library/selectors.html#selectors.BaseSelector.get_map) for instance, and the [SelectorKey](https://docs.python.org/3/library/selectors.html#selectors.SelectorKey) allows storing application-specific state in the `data` field if desired.
>
> this may require a bit more reorganization than the current patch, so could be deferred to a separate PR (if the performance impact is acceptable), but should be considered in a follow up.

_@tommilligan said in https://github.com/cherrypy/cheroot/pull/301#issuecomment-662916411:_
> I like the suggestion of refactoring how we manage connections a bit so that the use of `selectors` is more ergonomic - I have started looking at it. I need to think about it a bit more, as we also care about the **order** of the connections, and `selectors.get_map()` will just return an unordered mapping I think. Will keep thinking about it over the weekend.

**Comment by tommilligan** [comment]
Thanks. I've sunk a bit of time into this, what I have so far:

https://github.com/tommilligan/cheroot/pull/1 (PR on fork)

This has thrown up a couple of things:
- we can either store the `Connection`s ourself (ordered), or store them on `selectors` (unordered). Given in the latter case we have to store the order separately anyway, I'm inclined to just store them in our own structure
  - potentially we can just do this with an `OrderedDict[file-descriptor, Connection]`, but this will require a non-std module for lower python versions
- in the current PR, I get super flaky behaviour from `ConnectionManager`. This was reduced (but not eliminated) by adding some thread-safe locking around the manager's interactions with `selectors`.
  - I would be interested in some input on how `ConnectionManager` is shared/called, to think about other changes in design

**Comment by webknjaz** [comment]
@tommilligan looks reasonable. It is better if you create a draft PR here rather than in a fork. For others to see and have a consolidated discussion there.

As for the input, I don't really know what to add w/o digging into it myself. Introducing it was a part of refactoring by @the-allanc that was ultimately responsible for the regressions we got in 8.1.0 so you may assume that it's not ideal and keep digging deeper...

**Comment by liamstask** [comment]
added another take at https://github.com/cherrypy/cheroot/pull/309
