### ISSUE TITLE
timed_out_connections - dictionary changed size during iteration

### ISSUE THREAD

**Issue by Safihre** [cherrypy/cheroot#312]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
Traceback in the logs:
```python-traceback
Traceback (most recent call last):
  File "/opt/lib/python3.8/site-packages/cheroot/server.py", line 1795, in serve
    self.tick()
  File "/opt/lib/python3.8/site-packages/cheroot/server.py", line 2030, in tick
    self.connections.expire()
  File "/opt/lib/python3.8/site-packages/cheroot/connections.py", line 107, in expire
    for sock_fd, conn in timed_out_connections:
  File "/opt/lib/python3.8/site-packages/cheroot/connections.py", line 102, in <genexpr>
    timed_out_connections = (
  File "/opt/lib/python3.8/_collections_abc.py", line 743, in __iter__
RuntimeError: dictionary changed size during iteration
```

❓ **What is the motivation / use case for changing the behavior?**

💡 **To Reproduce**

💡 **Expected behavior**

📋 **Details**

📋 **Environment**

- Cheroot version: 8.4.4
- CherryPy version: 18.6.0 (if applicable)
- Python version: 3.8.X
- OS: NAS
- Browser: all

📋 **Additional context**

**Comment by Safihre** [comment]
Reported by a user with fresh install. Gathering more info about installed CherryPy/cheroot versions.

**Comment by Safihre** [comment]
@webknjaz I can now confirm this was introduced between 8.4.4 and 8.4.2, because I just updated `cheroot` on my own system and am also getting these problems now!

**Comment by Safihre** [comment]
Must be #309.

**Comment by webknjaz** [comment]
Yep, I think I know what the problem is.

**Comment by webknjaz** [comment]
https://github.com/cherrypy/cheroot/pull/309/files#r469927485

**Comment by webknjaz** [comment]
@liamstask ^

**Comment by webknjaz** [comment]
If somebody gets to sending a PR, the fix should be changing `get_map()` to `get_map().copy()` in all places where it's used. I'll probably be too busy today at least but will happily merge somebody else's PR if it's ready.

**Comment by webknjaz** [comment]
The fix has been released as v8.4.5: https://pypi.org/project/cheroot/8.4.5/.

Thanks to @liamstask @cyraxjoe for help!

**Comment by cyraxjoe** [comment]
The issue is _back_ from the depths of concurrency land.  https://github.com/cherrypy/cheroot/issues/317 @webknjaz do you prefer to keep this issue closed and use the new one?

**Comment by gora050** [comment]
> The fix has been released as v8.4.5: https://pypi.org/project/cheroot/8.4.5/.
> 
> Thanks to @liamstask @cyraxjoe for help!

Thanks! ;)

**Comment by jfindlay** [comment]
Confirmed that this issue was happening for me on ubuntu 20.04 with `python3-cherrypy3/focal 8.9.1-6 all` installed via apt and stopped happening with `CherryPy               18.6.0` installed via pip3.  Full context: I am using cherrypy as a backend for [salt netapi](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html)

**Comment by webknjaz** [comment]
@cyraxjoe let's use the new one.
