### ISSUE TITLE
Need to KeyboardInterrupt 3 times to stop the server

### ISSUE THREAD

**Issue by AbdealiJK** [cherrypy/cheroot#328]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
I am trying out cheroot for the first time today. When I run my flask application with cheroot, I find that to stop the application, I need to hit `Ctrl+C` 3 times - even if I wait for nearly 2-3 minutes and no requests are being processed.

❓ **What is the motivation / use case for changing the behavior?**
It intuitively stop if I hit the Ctrl+C once I think ?

💡 **To Reproduce**
```
$ mkdir -p /tmp/cheroottesting
$ cd /tmp/cheroottesting
$ python -m venv venv
$ venv/bin/pip install cheroot
$ cat app.py
from wsgiref.simple_server import make_server

def application(environ, start_response):
    status = '200 OK'
    response_headers = [('Content-type', 'text/plain')]
    start_response(status, response_headers)
    return [b"Hello World !"]
$ export PYTHONPATH=.
$ venv/bin/cheroot app:application -b 0.0.0.0:5000
```
What I observe:
![untitled](https://user-images.githubusercontent.com/2200743/94238865-93b65500-ff2e-11ea-8450-5062be20cb24.gif)

Note: I have tried to wait for about 30sec after hitting Ctrl-C for it to complete cleaning up after itself, didnt help much

💡 **Expected behavior**
The server should have stopped after I hit the first Ctrl-C

📋 **Details**
```
$ venv/bin/cheroot app:application --bind 0.0.0.0:5000

^CKeyboard Interrupt: shutting down


^CTraceback (most recent call last):
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1710, in safe_start
    self.start()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1819, in start
    self.serve()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1798, in serve
    self.tick()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 2038, in tick
    conn = self._connections.get_conn()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/connections.py", line 137, in get_conn
    in self._selector.select(timeout=0.01)
  File "/home/abdealijk/miniconda3/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/bin/cheroot", line 10, in <module>
    sys.exit(main())
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/cli.py", line 241, in main
    raw_args._wsgi_app.server(raw_args).safe_start()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1715, in safe_start
    self.stop()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 2071, in stop
    time.sleep(0.1)
KeyboardInterrupt


^CException ignored in: <module 'threading' from '/home/abdealijk/miniconda3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/abdealijk/miniconda3/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
```

📋 **Environment**
- Cheroot version: 8.4.5
- CherryPy version: Not using it
- Python version: 3.7.7
- OS: Windows 10 + Ubuntu 18.04.4 LTS in WSL2
- Browser: Not applicable

📋 **Additional context**
Maybe this is related to: https://github.com/cherrypy/cheroot/issues/323

**Comment by NathanRichard** [comment]
Hello all,
I was hit by this bug as well when upgrading from 8.4.0 to 8.4.5. According to my tests, the regression took place in 8.4.4 (the 8.4.3 being the latest ok version for me). The [changelog](https://github.com/cherrypy/cheroot/blob/master/CHANGES.rst#id29) indicates some changes in the shutdown procedure (PR 309). Maybe it is linked ?
I am running python 3.7.9 under Ubuntu 20.04.

**Comment by The-Compiler** [comment]
FWIW this also seems to affect SIGTERM, which causes the server to not exit at all (even when doing it multiple times).

**Comment by webknjaz** [comment]
Urgh... I would've merged one of the fixes but nobody seems to want to add tests

**Comment by The-Compiler** [comment]
Sorry, this was probably at least partially a false alarm. Here's an example closer to what I have in my project:

```python3
from wsgiref.simple_server import make_server
from cheroot.wsgi import WSGIServer
import os
import signal

def application(environ, start_response):
    status = '200 OK'
    response_headers = [('Content-type', 'text/plain')]
    start_response(status, response_headers)
    return [b"Hello World !"]


def main():
    print(f"PID: {os.getpid()}")
    signal.signal(signal.SIGTERM, lambda *args: server.stop())
    server = WSGIServer(('127.0.0.1', 1234), application)
    server.start()


if __name__ == '__main__':
    main()
```

I'm not actually sure why I added the custom signal handler, this was back in 2015 with cherrypy 3.8.0 and perhaps required at the time? It worked fine until cheroot 8.4.3, but when I remove it, SIGTERM seems to continue working with 8.4.4+ as well.

**Comment by webknjaz** [comment]
I'm pretty sure `from wsgiref.simple_server import make_server` is redundant there too. And yes, the signal handler is probably unnecessary. Although, I can imagine that it's problematic.
FWIW #331 / #322 need to be coupled with a pytest-based regression test.

**Comment by loqs** [comment]
@webknjaz did the cherrypy testsuite pass with either #331 or #322 for you?  Locally the same test from cherrypy/cherrypy#1873 was still failing with either applied.
