### ISSUE TITLE
cheroot rfile.read(size) intermittently fails if size == 0

### ISSUE THREAD

**Issue by mewalig** [cherrypy/cheroot#330]
**I'm submitting a ...**
- [ X ] bug report

**What is the current behavior?**
I used to use cherrypy with a patch to address https://github.com/cherrypy/cherrypy/issues/1602. After upgrading cherrypy, POST rfile read() intermittently fails. I am unable to reproduce this in isolation, but when running automated tests scripts that will hit the cherrypy server with requests, at some point the issue occurs

Below is an example error trace:
```
  File "C:\Users\Administrator\file-server\build\gxfs\out00-PYZ.pyz\cheroot.server", line 371, in read
  File "C:\Users\Administrator\file-server\build\gxfs\out00-PYZ.pyz\cheroot.makefile", line 170, in read
  File "C:\Users\Administrator\file-server\build\gxfs\out00-PYZ.pyz\cheroot.ssl.pyopenssl", line 133, in recv
  File "C:\Users\Administrator\file-server\build\gxfs\out00-PYZ.pyz\cheroot.ssl.pyopenssl", line 126, in _safe_call
UnreadablePostError: timed out
```

if I re-apply the changes described in https://github.com/cherrypy/cherrypy/issues/1602, the above errors go away. In particular, in cheroot/server.py:
```
274a275,277
>         if size == 0:
>             return b''
>
288a292,294
>             if size == 0:
>                 return b''
>
371,372c377,388
<         data = self.rfile.read(size)
<         self.remaining -= len(data)
---
>         if size == 0:
>             data = b''
>         else:
>             try: # this try block is unnecessary. leaving in to trace if bug recurs with non-zero size
>                 data = self.rfile.read(size)
>                 self.remaining -= len(data)
>             except Exception as esc:
>                 self.server.error_log(
>                     'error reading size ' + str(size) + ': ' + str(esc),
>                     level=logging.WARNING, traceback=True,
>                 )
>                 raise esc
389a406,408
>         if size == 0:
>             return b''
>
```

**Please tell us about your environment:**

- Cheroot version: 8.3.0
- CherryPy version: 17.4.2
- Python version: 2.7.17
- OS: Windows
- Browser: Chrome

**Comment by webknjaz** [comment]
I did some googleing and it looks like `UnreadablePostError` only exists in Django. So it seems like you use Cheroot (and possibly CherryPy) as a web-server for a Django App and this exception is raised by Django. I don't think we can do anything about things happening in other frameworks so I'm closing this issue.

**Comment by mewalig** [comment]
@webknjaz `UnreadablePostError` is the symptom, not the cause

What's the downside in just re-applying the changes described in cherrypy/cherrypy#1602, to explicitly handle the case where size == 0? Seems safer than always assuming the caller will never pass a size of 0.

**Comment by webknjaz** [comment]
I'm pretty sure it's applied.

**Comment by webknjaz** [comment]
But if you can prove that this is happening in an isolated CherryPy- or Cheroot-only example, I'll be happy to take a look at it.

**Comment by mewalig** [comment]
It is not applied-- see below. Is it safe to always assume that rfile.read(0) will never fail and will never return None? If not, more reason to apply.

cheroot/cheroot/server.py:269: size is not checked for zero value

``` 
    def read(self, size=None):
        """Read a chunk from ``rfile`` buffer and return it.
        :param int size: amount of data to read
        :returns: chunk from ``rfile``, limited by size if specified
        :rtype: bytes
        """
        data = self.rfile.read(size)
        self.bytes_read += len(data)
        self._check_length()
        return data
```

cheroot/cheroot/server.py:358: size is not checked for zero value
```
    def read(self, size=None):
        """Read a chunk from ``rfile`` buffer and return it.
        :param int size: amount of data to read
        :rtype: bytes
        :returns: chunk from ``rfile``, limited by size if specified
        """
        if self.remaining == 0:
            return b''
        if size is None:
            size = self.remaining
        else:
            size = min(size, self.remaining)

        data = self.rfile.read(size)
        self.remaining -= len(data)
        return data
```
