### ISSUE TITLE
Insufficient arguments are passed while calling handle_no_ssl method. 

### ISSUE THREAD

**Issue by dhanavaths** [cherrypy/cheroot#34]
![cheroot_api_error](https://user-images.githubusercontent.com/17666008/27399934-16371f18-56dc-11e7-83a4-5ff7f7f0f596.png)

Please refer the the image attached. have taken this screenshot from cheroot/server.py file.

Is it possible to log an error to server logger when worker exits for unexpected reasons? All threads in threadpool has exited in our cherrypy web server and no requests were served(have checked it with the help of all python threads stackdump). I am expecting that its happening due to arguments mismatch.

**Comment by webknjaz** [comment]
Could you please be more clear about what's happening? Any code snippets? (normal code block, not a picture).

P.S. Making screenshots is pointless while you may add a searchable code snippet and/or send links to the certain lines of code right on GitHub.

**Comment by dhanavaths** [comment]
code snippet:

`
@/usr/local/lib/python2.7/dist-packages/cheroot/server.py
class HTTPConnection:
    def communicate(self):
        """Read each request and respond appropriately."""
        request_seen = False
        try:
            while True:
                # (re)set req to None so that if something goes wrong in
                # the RequestHandlerClass constructor, the error doesn't
                # get written to the previous request.
                req = None
                req = self.RequestHandlerClass(self.server, self)

                # This order of operations should guarantee correct pipelining.
                req.parse_request()
                if self.server.stats['Enabled']:
                    self.requests_seen += 1
                if not req.ready:
                    # Something went wrong in the parsing (and the server has
                    # probably already made a simple_response). Return and
                    # let the conn close.
                    return

                request_seen = True
                req.respond()
                if req.close_connection:
                    return
        except socket.error as ex:
            errnum = ex.args[0]
            # sadly SSL sockets return a different (longer) time out string
            if (
                errnum == 'timed out' or
                errnum == 'The read operation timed out'
            ):
                # Don't error if we're between requests; only error
                # if 1) no request has been started at all, or 2) we're
                # in the middle of a request.
                # See https://github.com/cherrypy/cherrypy/issues/853
                if (not request_seen) or (req and req.started_request):
                    # Don't bother writing the 408 if the response
                    # has already started being written.
                    if req and not req.sent_headers:
                        try:
                            req.simple_response('408 Request Timeout')
                        except errors.FatalSSLAlert:
                            # Close the connection.
                            return
                        except errors.NoSSLError:
                            self._handle_no_ssl()
            elif errnum not in errors.socket_errors_to_ignore:
                self.server.error_log('socket.error %s' % repr(errnum),
                                      level=logging.WARNING, traceback=True)
                if req and not req.sent_headers:
                    try:
                        req.simple_response('500 Internal Server Error')
                    except errors.FatalSSLAlert:
                        # Close the connection.
                        return
                    except errors.NoSSLError:
                        self._handle_no_ssl()
            return
        except (KeyboardInterrupt, SystemExit):
            raise
        except errors.FatalSSLAlert:
            # Close the connection.
            return
        except errors.NoSSLError:
            self._handle_no_ssl(req)
        except Exception as ex:
            self.server.error_log(repr(ex), level=logging.ERROR, traceback=True)
            if req and not req.sent_headers:
                try:
                    req.simple_response('500 Internal Server Error')
                except errors.FatalSSLAlert:
                    # Close the connection.
                    return

    linger = False

    def _handle_no_ssl(self, req):
        if not req or req.sent_headers:
            return
        # Unwrap wfile
        self.wfile = MakeFile(self.socket._sock, 'wb', self.wbufsize)
        msg = (
            'The client sent a plain HTTP request, but '
            'this server only speaks HTTPS on this port.'
        )
        req.simple_response('400 Bad Request', msg)
        self.linger = True
`

_handle_no_ssl expects two arguments but some of the callers are passing only one argument(self). 

I use cherry to host our webserver. I have set 64 as minimum thread count. At the start of the service I see 64 threads in pool but all of them exit over the time. Attaching our process stackdump for your reference.
[webserver_stackdump.txt](https://github.com/cherrypy/cheroot/files/1093684/webserver_stackdump.txt)
 
I am expecting that threads in threadpool are exiting with TypeError due to mismatch in argument count. I have added traceback to know the exact reason for threadpool exit. I will keep you updated if I see this problem again.

**Comment by webknjaz** [comment]
I meant posting your app and traceback as a snippet.
