### ISSUE TITLE
[8.4.8 regression?] ConnectionResetError on Windows

### ISSUE THREAD

**Issue by The-Compiler** [cherrypy/cheroot#341]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
After updating from 8.4.7 to .8, in around 50% of the testsuite runs of [my project](https://www.qutebrowser.org/) (which runs end to end tests of a webbrowser against cheroot), I get this traceback on Windows:

```python-traceback
Exception in thread CP Server Thread-6:
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\a\qutebrowser\qutebrowser\.tox\py37-pyqt515\lib\site-packages\cheroot\workers\threadpool.py", line 130, in run
    conn.close()
  File "D:\a\qutebrowser\qutebrowser\.tox\py37-pyqt515\lib\site-packages\cheroot\server.py", line 1357, in close
    self._close_kernel_socket()
  File "D:\a\qutebrowser\qutebrowser\.tox\py37-pyqt515\lib\site-packages\cheroot\server.py", line 1480, in _close_kernel_socket
    shutdown(socket.SHUT_RDWR)  # actually send a TCP FIN
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

💡 **To Reproduce**
I'm afraid I don't have a reproducer for this at the moment, and no idea where to start...

📋 **Environment**
- Cheroot version: 8.4.8
- Python version: 3.7.9
- OS: Windows Server 2019 (via GitHub Actions)

📋 **Additional context**
Failing builds:

- https://github.com/qutebrowser/qutebrowser/pull/5924/checks?check_run_id=1473349077
- https://github.com/qutebrowser/qutebrowser/runs/1460847930

I don't remember ever seeing this before 8.4.8, so #337 might be responsible for this somehow? (cc @liamstask)

**Comment by webknjaz** [comment]
Thanks for reporting! Here's the test report from a similar env https://github.com/cherrypy/cheroot/runs/1471515239?check_suite_focus=true and it looks fine.

Also, cc @cyraxjoe who modified `_close_kernel_socket` recently IIRC.

@The-Compiler it looks like the traceback originates from `socket.shutdown()` when it tries to finalize the session on the transport level. I can imagine that this may be happening when the client has already interrupted the connection and we attempt to send the shutdown sequence (although I don't have a windows machine to reproduce myself).

I see that there's already some code that attempts to suppress some cases: https://github.com/cherrypy/cheroot/blob/a8324f5/cheroot/server.py#L1479-L1484. It uses `errno.ENOTCONN` but in your case `errno.ECONNRESET` seems to be happening. I'd add it to the check + maybe add `errno.EPIPE`/`errno.ESHUTDOWN`. Python 3 actually has nice subclasses from these cases that we may migrate to in Cheroot v9: https://docs.python.org/3/library/exceptions.html#ConnectionError.

P.S. I don't see any reason why these tracebacks would leak into your test suite status... My understanding is that it'd only create annoying log entries...

**Comment by webknjaz** [comment]
@The-Compiler mind trying out https://github.com/cherrypy/cheroot/pull/342 in your CI setup?

**Comment by webknjaz** [comment]
Interesting... This message https://bugs.python.org/msg186417 seems to imply that the client can send RST if it sent some bytes over the wire that the server never read but instead initiated the TCP session termination with FIN.

**Comment by The-Compiler** [comment]
> P.S. I don't see any reason why these tracebacks would leak into your test suite status... My understanding is that it'd only create annoying log entries...

With those end2end tests (starting qutebrowser and a cheroot+Flask server as a subprocess each), I treat any unexpected line on stdout as an error, as I'm essentially parsing the stdout (to e.g. see whether the logged requests matched what I expected). So that's entirely my own fault :smile: 

> mind trying out #342 in your CI setup?

Thanks for the quick follow-up! I'll give it a try ASAP (probably tomorrow).
