### ISSUE TITLE
[TODO] 👷 Kill Travis CI in favor of GHA 

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#343]
❓ **I'm submitting a ...**
- [ ] 🐞 bug report
- [X] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Is your feature request related to a problem? Please describe.**

We've burnt through the trial credits and now the builds are disabled ([https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing](https://web.archive.org/web/*/https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) / [https://blog.travis-ci.com/oss-announcement](https://web.archive.org/web/20201125145802/https://blog.travis-ci.com/oss-announcement))

🐣 **Describe the solution you'd like**

Fully migrate to GHA

📋 **Describe alternatives you've considered**

Beg for free OSS credits (time-consuming and not guarantees).

📋 **Additional context**

https://webknjaz.me/prose/et-tu-brute-use-travis-ci-for-foss-no-more/

**Comment by jaraco** [comment]
I've dropped support for Travis in jaraco/skeleton. I have no objections.

**Comment by webknjaz** [comment]
I've committed some changes to master already but PyPy support needs to be polished a bit, I have some experiments in a separate branch.
