### ISSUE TITLE
PyPy fixed a bug with tox, cheroot can re-enable CI run

### ISSUE THREAD

**Issue by mattip** [cherrypy/cheroot#373]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
I am not sure if this is a bug or some other category. In this line
https://github.com/cherrypy/cheroot/blob/7af66b0ebff15eae52f9a01b4f9584906a816e90/.github/workflows/python-tests.yml#L46
an issue is mentioned that was fixed a while ago, so the pypy-windows CI runs can be re-enabled.

❓ **What is the motivation / use case for changing the behavior?**

More complete CI testing

📋 **Additional context**

Over at [PyPy](https://www.pypy.org/contact.html) we would love to hear about use of cherrypy with PyPy - does it show any pain points? Work on all platforms?

**Comment by webknjaz** [comment]
Feel free to send a PR and we'll see if it's still failing. Personally, I don't use PyPy normally but still try to support it in my projects to the extent CI allows.

**Comment by webknjaz** [comment]
> an issue is mentioned that was fixed a while ago, so the pypy-windows CI runs can be re-enabled.

I'm trying to re-enable those jobs but it's not as trivial. We depend on cryptography that doesn't provide wheels for PyPy 2.7 and installing the build deps doesn't seem easy. Taking into account that Python 2 support will be dropped, it shouldn't be too problematic.
I'll also check if I can do anything about other exclusions.

> Over at [PyPy](https://www.pypy.org/contact.html) we would love to hear about use of cherrypy with PyPy - does it show any pain points? Work on all platforms?

Mostly with testing in public CIs. Specifically old hacks for py2.7.

**Comment by webknjaz** [comment]
Resolved via https://github.com/cherrypy/cheroot/commit/f82aee613ca4f7c0ae80452fedc95b7a89b207d1.
