### ISSUE TITLE
Broken links?

### ISSUE THREAD

**Issue by mar10** [cherrypy/cheroot#392]
Just in case you didn't notice yet: the homepage link is broken, since [cherrypy.org](https://cheroot.cherrypy.org/) is owned by someone else and should be https://cheroot.cherrypy.dev ?

![image](https://user-images.githubusercontent.com/41663/136824452-6bd6f782-097e-4af7-992f-754ac880eded.png)

**Comment by webknjaz** [comment]
Yes, you're right, context: https://github.com/cherrypy/cherrypy/issues/1872.

**Comment by webknjaz** [comment]
This is fixed, AFAICT.
