### ISSUE TITLE
[TODO] Remove the integration with PyUp

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#464]
❓ **I'm submitting a ...**
- [x] 📋 task

🐞 **Is your feature request related to a problem? Please describe.**

I tried doing this myself by removing the @pyup-bot user from collaborators but it keeps coming back being re-added by @jaraco: https://github.com/organizations/cherrypy/settings/audit-log?q=action%3Arepo.add_member.
I removed the config from the repo and I also tried removing my own account in the PyUp service and revoking the OAuth App integration https://github.com/settings/applications which does nothing.
And the PyUp web dashboard does not let me remove the repos — the `remove` menu item is disabled with a tooltip saying `This repo was added by jaraco. You can't remove it.`

🐣 **Describe the solution you'd like**

@jaraco could you go to https://pyup.io/account/repos/github/cherrypy/cheroot/settings/ and remove the integration there? While at it, maybe also drop it for CherryPy too. I'll probably be building a proper GHA-based solution for upgrading the pins soon but right now this service sends us (partially) invalid PRs so I'd rather disable it already.

📋 **Describe alternatives you've considered**

Keep suffering the bot's activity?

📋 **Additional context**

I'm pretty sure that the integration on PyUp side is aggressively re-adding the bot user as a repository collaborator through the connection in @jaraco's account. Removing it at https://github.com/settings/applications should prevent such hostility too.

**Comment by jaraco** [comment]
I don't see anything about PyUp under integrations:

![image](https://user-images.githubusercontent.com/308610/148668519-ccc21e5f-6253-4c8b-bb40-882e2fe6d6ea.png)

Nor webhooks:

![image](https://user-images.githubusercontent.com/308610/148668529-0d1242e3-8eea-495a-bd7a-a89e9a65490c.png)

**Comment by webknjaz** [comment]
@jaraco it's not a GH App but an old-fashioned webhook-based thing @ https://github.com/settings/applications — it's connected through your user account, not the org. Plus @ https://pyup.io/account/repos/github/cherrypy/cheroot/.

**Comment by jaraco** [comment]
I logged into PyUp.io and removed CherryPy and Cheroot repos.
