### ISSUE TITLE
Need support for certificate FILETYPE_ASN1

### ISSUE THREAD

**Issue by jimkimball** [cherrypy/cheroot#48]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

I would call this a new feature.

* **What is the current behavior?**

Currently, cheroot hardcodes the certificate as FILETYPE_PEM in two places. The first in the call to SSL.Context.use_certificate_file() by not passing the FILETYPE parameter. The second is in the call to crypto.load_certificate() where FILETYPE_PEM is hard-coded.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

Since both FILETYPEs exist, it would be nice for cheroot to support them.

* **Please tell us about your environment:**

- Python version: 2.7
- Cheroot version: 5.7.0
- CherryPy version: X.X.X (if applicable)
- OS: Windows 7 (I know...)
- Browser: Chrome  57.0.2987.133 (64-bit)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
@jaraco you recently looked into SSL, what can you say about this?

**Comment by jaraco** [comment]
It seems reasonable to support. I’m not familiar enough with the interface to add any insight. Someone would need to investigate and propose an implementation that could either autodetect the type or present an interface to solicit that value from the user. It’s possible such an interface already exists with the context object, but I don’t recall.
