### ISSUE TITLE
wsgi.Server reports CherryPy version

### ISSUE THREAD

**Issue by mar10** [cherrypy/cheroot#5]
As I understand it, Cheroot brings a standalone server with seperate versioning (e.g. 5.1), but 
`cheroot.wsgi.Server.version` returns either "CherryPy/undefined" or "CherryPy/10.1.1", depending on the additional cherrypy package beeing installed or not.

**Comment by webknjaz** [comment]
You are right, this should be fixed. We'd appreciate a PR if possible :)
