### ISSUE TITLE
Cheroot 5.9.1 has invalid files

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#61]
Yegor Y. sent me an e-mail reporting an issue with the cheroot 5.9.1 package. It contains invalid files like "test_core_BACKUP_1440.py". These files cause issues in compilation.

These files were not intended to be in the distribution. They happened to be on my machine when I cut the release manually. I cut the release manually because the CI process takes half an eternity to complete.

I'll cut a new 5.9.2 release to correct the issue.

**Comment by jaraco** [comment]
I've cut a new release (two actually), but it hasn't gone out yet due to #63 and #64.

**Comment by jaraco** [comment]
Fixed in subsequent releases.

**Comment by webknjaz** [comment]
@jaraco let's integrate `setuptools-git` to avoid messing around `MANIFEST.in`

**Comment by jaraco** [comment]
We’re using setuptools_scm. Manifest.in isn’t there or if it is, it can be removed. The reason the files appeared was because they were on my machine when I built a manual release... and distutils picks up all .py files regardless of the finders or manifest.in. I don’t think there’s more to be done here.

**Comment by webknjaz** [comment]
@jaraco AFAIK `setuptools-scm` only provides a way to look-up dist version, but not a list of files.

**Comment by webknjaz** [comment]
I've re-checked with https://github.com/pypa/setuptools_scm and didn't find anything mentioning that it provides any integration for tracking files.

**Comment by webknjaz** [comment]
https://github.com/msabramo/setuptools-git on the other hand provides such integration.

**Comment by jaraco** [comment]
setuptools_scm implements [file finders](https://github.com/pypa/setuptools_scm/blob/2521712ff13183a6bca7147a03ddd630795f3dd4/setup.py#L72) and is the tool supported and endorsed by the PyPA for facilitating file finding an version inference for git and Mercurial repos. It's what I've been using on every project I maintain ever since I merged [hgtools](/jaraco/hgtools), a derivative of [setuptools_hg](https://bitbucket.org/jezdez/setuptools_hg/wiki/Home), with setuptools_scm.

Unless you can illustrate something that setuptools-git does that setuptools_scm doesn't do and can'd do readily, then I'd much prefer to stick to setuptools_scm.

**Comment by webknjaz** [comment]
Okay, now I see. But if file finder only adds git-tracked files does this mean that you unintentionally `git add`ed that file?
My point is that none of untracked files should be recognised/added during the dist creation.

**Comment by jaraco** [comment]
Ahh. No - the files were never `git add`ed. The reason they appeared in the dist is because even if file finders are used, distutils always includes all .py files, regardless of what the manifest or file finders include.

**Comment by jaraco** [comment]
Aha. So those files would have been pulled in (by distutils) because they are .py files _and_ because they're in a package:

```
$ tree
.
├── cheroot
│   ├── __init__.py
│   └── test
│       ├── __init__.py
│       └── test_core_backup.py
└── setup.py

2 directories, 4 files
$ cat setup.py
__import__('distutils.core').core.setup(name='foo', version='1.0', packages=['cheroot', 'cheroot.test'])
$ python setup.py sdist 2> /dev/null | grep backup             
hard linking cheroot/test/test_core_backup.py -> foo-1.0/cheroot/test
```

**Comment by webknjaz** [comment]
Fair enough. If you'll have any ideas on how to avoid this I'd like to implement smth to protect us from such accidents :)

**Comment by jaraco** [comment]
Well, the main way to avoid it is to always cut releases in CI, which is the recommended procedure. So making the automated release process nimble and fast should largely obviate this issue.
