### ISSUE TITLE
linkcheck job failing due to utcc.utoronto.ca being down

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#629]
While working on #505, I notice that tests are failing in the linkcheck-docs job:

```
(         history: line  237) broken    https://utcc.utoronto.ca/~cks/space/blog/linux/SocketAbstractNamespace - HTTPSConnectionPool(host='utcc.utoronto.ca', port=443): Max retries exceeded with url: /~cks/space/blog/linux/SocketAbstractNamespace (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f863cfceb00>, 'Connection to utcc.utoronto.ca timed out. (connect timeout=None)'))
build finished with problems.
ERROR: InvocationError for command /home/runner/work/cheroot/cheroot/.tox/linkcheck-docs/bin/python -bb -E -s -m sphinx -j auto -a -n -W --keep-going -b linkcheck --color -d /home/runner/work/cheroot/cheroot/.tox/.tmp/.doctrees . /home/runner/work/cheroot/cheroot/.tox/docs_out (exited with code 1)
ERROR: invocation failed (exit code 1)
✖ FAIL linkcheck-docs in 9 minutes, 14.912 seconds
```

I tried navigating to that link and indeed it's unresponsive at the moment. Who knows if it's transient or permanent.

**Comment by webknjaz** [comment]
Things like this can be ignored via `linkcheck_ignore` in `conf.py`. Though I'd probably replace it with a web archive reference..

**Comment by webknjaz** [comment]
> Who knows if it's transient or permanent.

I've just opened the link and it works for me. I wonder if this is related to the release of urllib3 v2.0 that's been causing TLS problems across many RTD projects under Python 3.7 (in those cases updating to Python 3.11 helped). I don't remember if I pinned this specific toxenv, let me see...

**Comment by webknjaz** [comment]
Looks like this hasn't been failing for a while: https://github.com/cherrypy/cheroot/actions?query=event%3Apush+branch%3Amain. Closing.
