### ISSUE TITLE
Tests take too long to run

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#63]
It shouldn't take two hours to cut a release.

![image](https://user-images.githubusercontent.com/308610/33186207-cd499094-d055-11e7-9c61-f5171c1cc5e8.png)

**Comment by jaraco** [comment]
I think testing on just mainstream Python will be sufficient to catch most issues.

**Comment by webknjaz** [comment]
Let me solve this differently w/o completely removing those envs.
