### ISSUE TITLE
TypeError in catch exception ssl.SSLerror 

### ISSUE THREAD

**Issue by hevel** [cherrypy/cheroot#73]
* **I'm submitting a bug report**

I got traceback error.
```python
cheroot/server.py line 1515, in start
cheroot/server.py line 1590, in tick
cheroot/ssl/builtin.py line 100, in wrap
TypeError: argument of type 'int' is not iterable
```
builtin.py line 100 code:
```
elif 'handshake operation timed out' in ex.args[0]:
```

- Python version: 2.7.11
- Cheroot version: 5.8.3
- CherryPy version: 11.0.0 (if applicable)
- OS: debian7.7
- Apache-HttpClient/4.2.1 (java 1.5)

**Comment by webknjaz** [comment]
Could you please trace what value `ex.args` holds?
And also provide us with the STR.

**Comment by calmkart** [comment]
exception ssl.SSLError

    Raised to signal an error from the underlying SSL implementation (currently provided by the OpenSSL library). This signifies some problem in the higher-level encryption and authentication layer that’s superimposed on the underlying network connection. This error is a subtype of socket.error, which in turn is a subtype of IOError. The error code and message of SSLError instances are provided by the OpenSSL library.


builtin.py
74   except ssl.SSLError as ex:
....
100  elif 'handshake operation timed out' in ex.args[0]:
ex.args[0] is errorcode
ex.args[1] is error message

100 elif 'handshake operation timed out' in ex.args[1]:
if ok

**Comment by webknjaz** [comment]
Makes sense, thank you
