### ISSUE TITLE
Cheroot uses _pyio incorrectly

### ISSUE THREAD

**Issue by bangorr** [cherrypy/cheroot#84]
Attempting to use Cheroot (via CherryPy) on Cygwin has revealed that Cheroot imports a private module, _pyio. "Outside" use of _pyio this way is not supported.

CherryPy should use a different module or interface for this functionality (https://github.com/cherrypy/cheroot/blob/86c6b246ec7cb704c6f96123556db1a083301634/cheroot/makefile.py#L5).

A side-effect of fixing this issue is that this may help CherryPy run on Cygwin once again.

See https://bugs.python.org/issue32287 for more discussion or context.

(originally posted here: https://github.com/cherrypy/cherrypy/issues/1704#issuecomment-381174191)

**Comment by webknjaz** [comment]
Fixed by df203590fc4d555ad5f98dcd0ebc850c5b4993d4

**Comment by webknjaz** [comment]
@bangorr it's on PYPI now: https://pypi.org/project/Cheroot/6.2.2/
