### ISSUE TITLE
get the access log

### ISSUE THREAD

**Issue by boumboum** [cherrypy/cheroot#89]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository

Is there any way to display (and optionally write to a file) the access log?
If yes, how?
If not, would it possible in the near future?

* **Please tell us about your environment:**
- Python version: 3.6.4
- Cheroot version: 6.2.4
- OS: Windows

**Comment by webknjaz** [comment]
Not at this point. But CherryPy implements this on a higher level.
