### ISSUE TITLE
Make Python 2 behave closer to Python 3 standard behavior

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#90]
Add the following snippet to the top of all modules:

```python
from __future__ import absolute_import, division, print_function, unicode_literals
__metaclass__ = type
```

* **I'm submitting a ...**
- [ ] bug report
- [X] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
code cross-compatibility improvement for better Python 3/2 support.

* **What is the current behavior?**
Has old-style classes. Python 2-centric syntax present.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

* **What is the expected behavior?**
New-style classes by default. New syntax all over the place.

* **What is the motivation / use case for changing the behavior?**
Make project code in Python 2 env behave more like Python 3.

* **Please tell us about your environment:**

- Cheroot version: master branch
- CherryPy version: N/A
- Python version: N/A
- OS: N/A
- Browser: N/A

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
Ageed via Gitter: https://gitter.im/cherrypy/cherrypy?at=5ae1d28f60ddf96c97e3eed3
cc: @jaraco

**Comment by webknjaz** [comment]
People on the Internet spot a few issues with `unicode_literals`: http://python-future.org/unicode_literals.html#against-unicode-literals

@jaraco should we consider not using it?

**Comment by jaraco** [comment]
I agree that `unicode_literals` is the one future compatibilty with the most pitfalls. I’ve encountered some of those myself. It’s definitely not the kind of change you can make without the consideration for the consequences. However, in most cases (and I’ve done it with many legacy projects), its use has no adverse consequences. It’s those cases where the system expects `str` on Python 2 and Python 3. The libraries that expect such a thing (Setuptools is one such culprit) are at fault here and should be corrected. In most cases, simply wrapping the values with `str(…)` right before passing to the offending call is sufficient (as it’s a no-op on Python 3 and will encode using default encoding on Python 2). So for example, with WSGI and HTTP headers, if they're not explicitly encoding, then they're probably relying on a least-specific encoding like latin-1 or ascii. So if encoding does matter, then the software should adapt and be specific about the encoding (on both Python 2 and 3).

I do feel strongly that using `unicode_literals` is the right thing to do. I also recognize that CherryPy, like other web frameworks, is subject to some of the less-than-ideal decisions made around WSGI and text headers. And so we should be cautious about `unicode_literals` and only apply them where we have confidence that the code will operate properly (either by careful review of the module's code or by validating that the tests exercise the functionality sufficiently). If that's too high a burden (overall or for a particular module), I'll have no problem deferring that work for later (possibly never).

**Comment by webknjaz** [comment]
Unstale
