### ISSUE TITLE
Unix socket mode not set to 0o777

### ISSUE THREAD

**Issue by hvenev** [cherrypy/cheroot#93]
Currently, cheroot deletes any pre-existing AF_UNIX socket file, then attempts to chmod the now non-existent file to 0o777, and only then creates it.

The correct behaviour would be to chmod the socket after creating it.

**Comment by webknjaz** [comment]
Hm.. It was there from the very beginning: https://github.com/cherrypy/cheroot/commit/6ced9fd2f7d23c9e4db78894d616ed8cc5e83738#diff-920de15fced9e5f9697efed08f3c207dR214

**Comment by webknjaz** [comment]
@hvenev feel free to review #110

**Comment by hvenev** [comment]
This is certainly an improvement over the old behaviour.

Interestingly, the old behaviour also had a security vulnerability: If cherrypy is running as root and the socket is in /tmp/, a process might put a symlink to a system file between the `unlink` and the `chmod`, and trick cherrypy into making the file writeable.

Now chmod() only happens after we're certain the file has been created by us. Assuming another user can't delete/move the socket and put something else in its place (which is forbidden for `/tmp`), this should no longer be a problem.

Still, if you're feeling paranoid, you might want to set `os.chmod(..., follow_symlinks=False)`. This only applies if the socket is in a directory owned by an untrusted user, which is very hard to get secure.

While writing this, I found a better option: call `chmod` on the socket before `bind`:

    os.fchmod(socket.fileno(), 0o777)
    socket.bind(path)

In this case `bind()` will create a socket file with mode 777 without having to fix it later.

**Comment by webknjaz** [comment]
@hvenev thanks for the feedback! Please write the further reviews on PR page to help track all related info in one place :)

I'll think how we could combine the info you provided into patch improvement.

**Comment by webknjaz** [comment]
Another interesting post: https://github.com/python/asyncio/issues/426#issuecomment-326928071
